exapp/config/routes.rb
Rails.application.routes.draw do
  resources :test_results
  resources :users
  resources :what_tests
  resources :periods

  get '/' => 'test_results#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

exapp/app/models/test_result.rb
class TestResult < ApplicationRecord
  belongs_to :user
  belongs_to :what_test

  validates :user_id,:what_test_id,:jpn ,:math ,:eng ,:sci ,:soc, presence: true
  validates :jpn ,:math ,:eng ,:sci ,:soc, inclusion: {in: 0..100}

  def self.search(search)
    if search #Controllerから渡された荒メータが!=nillの場合は、titleカラムを部分一致検索
      redirect_to test_results_path
    end

    TestResult.all
    end
end

exapp/app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_action :set_test_result, only: [:show, :edit, :update, :destroy]

  # GET /test_results
  # GET /test_results.json
  def index
    if params[:search]
      @grade_results = TestResult.joins(:user).where(:users => {:grade => params[:search]})
    else
      @grade_results = TestResult.joins(:user).where(:users => {:grade => nil})
    end
    @test_results = TestResult.all
  end

  # GET /test_results/1
  # GET /test_results/1.json
  def show
  end

  # GET /test_results/new
  def new
    @test_result = TestResult.new
  end

  # GET /test_results/1/edit
  def edit
  end

  # POST /test_results
  # POST /test_results.json
  def create
    @test_result = TestResult.new(test_result_params)

    respond_to do |format|
      if @test_result.save
        format.html { redirect_to @test_result, notice: 'テストデータ作成完了' }
        format.json { render :show, status: :created, location: @test_result }
      else
        format.html { render :new }
        format.json { render json: @test_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_results/1
  # PATCH/PUT /test_results/1.json
  def update
    respond_to do |format|
      if @test_result.update(test_result_params)
        format.html { redirect_to @test_result, notice: 'テスト結果作成完了.' }
        format.json { render :show, status: :ok, location: @test_result }
      else
        format.html { render :edit }
        format.json { render json: @test_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_results/1
  # DELETE /test_results/1.json
  def destroy
    @test_result.destroy
    respond_to do |format|
      format.html { redirect_to test_results_url, notice: 'テスト結果を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_result
      @test_result = TestResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_result_params
      params.require(:test_result).permit(:user_id, :what_test_id, :jpn, :math, :eng, :sci, :soc)
    end
end

exapp/app/helpers/test_results_helper.rb
module TestResultsHelper
end

exapp/app/views/test_results/_form.html.erb
<%= form_with(model: test_result, local: true) do |form| %>
  <% if test_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_result.errors.count, "error") %> prohibited this test_result from being saved:</h2>

      <ul>
      <% test_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id,'ユーザ名' %>
    <%= form.collection_select :user_id, User.all ,:id,:name,{include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :what_test_id,'テスト種目' %>
    <%= form.collection_select :what_test_id, WhatTest.joins(:period).all ,:id,:periodname_and_testname,{include_blank: true} %>
  </div>

  <div class="field">
    <%= form.label :jpn,'国語' %>
    <%= form.number_field :jpn %>
  </div>

  <div class="field">
    <%= form.label :math,'数学' %>
    <%= form.number_field :math %>
  </div>

  <div class="field">
    <%= form.label :eng,'英語' %>
    <%= form.number_field :eng %>
  </div>

  <div class="field">
    <%= form.label :sci,'理科' %>
    <%= form.number_field :sci %>
  </div>

  <div class="field">
    <%= form.label :soc,'社会' %>
    <%= form.number_field :soc %>
  </div>

  <div class="actions">
    <%= form.submit "作成" %>
  </div>
<% end %>

exapp/app/views/test_results/edit.html.erb
<h1>テストデータ編集画面</h1>

<%= render 'form', test_result: @test_result %>

<%= link_to '詳細', @test_result %> |
<%= link_to '戻る', test_results_path %>

exapp/app/views/test_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>テストデータ</h1><%= link_to 'テストデータ入力', new_test_result_path, {:class => "btn btn-primary"} %>

<table class="table">
  <thead>
  <tr>
    <th>生徒名</th>
    <th>学年</th>
    <th>期間</th>
    <th>テスト名</th>
    <th>国語</th>
    <th>数学</th>
    <th>英語</th>
    <th>理科</th>
    <th>社会</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @test_results.each do |test_result| %>
    <tr>
      <td><%= test_result.user.name %></td>
      <td><%= test_result.user.grade %></td>
      <td><%= test_result.what_test.period.periodname %></td>
      <td><%= test_result.what_test.testname %></td>
      <td><%= test_result.jpn %></td>
      <td><%= test_result.math %></td>
      <td><%= test_result.eng %></td>
      <td><%= test_result.sci %></td>
      <td><%= test_result.soc %></td>
      <td><%= link_to '詳細', test_result, {:class => "btn btn-primary"} %></td>
      <td><%= link_to '編集', edit_test_result_path(test_result), {:class => "btn btn-primary"} %></td>
      <td><%= link_to '削除', test_result, method: :delete, data: {confirm: '削除しますか?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<h2>学年別テストデータ</h2>

<%= form_tag test_results_path, :method => 'GET' do %>

  <p>
    <%= select :search, params[:search], {"1年" => 1, "2年" => 2, "3年" => 3, "4年" => 4, "5年" => 5, "6年" => 6}, :prompt => "学年を選択してください" %>
    <!-- <%= text_field_tag :search, params[:search] %> -->
    <%= submit_tag "検索", {:grade => params[:search]} => nil %>
  </p>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th>生徒名</th>
    <th>学年</th>
    <th>期間</th>
    <th>テスト名</th>
    <th>国語</th>
    <th>数学</th>
    <th>英語</th>
    <th>理科</th>
    <th>社会</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @grade_results.each do |grade_result| %>
    <tr>
      <td><%= grade_result.user.name %></td>
      <td><%= grade_result.user.grade %></td>
      <td><%= grade_result.what_test.period.periodname %></td>
      <td><%= grade_result.what_test.testname %></td>
      <td><%= grade_result.jpn %></td>
      <td><%= grade_result.math %></td>
      <td><%= grade_result.eng %></td>
      <td><%= grade_result.sci %></td>
      <td><%= grade_result.soc %></td>
      <td><%= link_to '詳細', grade_result %></td>
      <td><%= link_to '編集', edit_test_result_path(grade_result) %></td>
      <td><%= link_to '削除', grade_result, method: :delete, data: {confirm: '削除しますか?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

exapp/app/views/test_results/new.html.erb
<h1>テストデータ入力フォーム</h1>

<%= render 'form', test_result: @test_result %>

<%= link_to '戻る', test_results_path %>

exapp/app/views/test_results/show.html.erb
<h1>  <%= @test_result.user.name %> のテストデータ詳細画面</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>生徒名:</strong>
  <%= @test_result.user.name %>
</p>

<p>
  <strong>テスト種目:</strong>
  <%= @test_result.what_test.testname %>
</p>

<p>
  <strong>国語:</strong>
  <%= @test_result.jpn %>
</p>

<p>
  <strong>数学:</strong>
  <%= @test_result.math %>
</p>

<p>
  <strong>英語:</strong>
  <%= @test_result.eng %>
</p>

<p>
  <strong>理科:</strong>
  <%= @test_result.sci %>
</p>

<p>
  <strong>社会:</strong>
  <%= @test_result.soc %>
</p>

<%= link_to '編集', edit_test_result_path(@test_result) %> |
<%= link_to '戻る', test_results_path %>