exapp/config/routes.rb
Rails.application.routes.draw do
  resources :test_results
  resources :users
  resources :what_tests
  resources :periods

  get '/' => 'test_results#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

exapp/app/models/what_test.rb
class WhatTest < ApplicationRecord
  belongs_to :period

  def periodname_and_testname
    period.periodname + testname
  end
end

exapp/app/controllers/what_tests_controller.rb
class WhatTestsController < ApplicationController
  before_action :set_what_test, only: [:show, :edit, :update, :destroy]

  # GET /what_tests
  # GET /what_tests.json
  def index
    @what_tests = WhatTest.all
  end

  # GET /what_tests/1
  # GET /what_tests/1.json
  def show
  end

  # GET /what_tests/new
  def new
    @what_test = WhatTest.new
  end

  # GET /what_tests/1/edit
  def edit
  end

  # POST /what_tests
  # POST /what_tests.json
  def create
    @what_test = WhatTest.new(what_test_params)

    respond_to do |format|
      if @what_test.save
        format.html { redirect_to @what_test, notice: 'What test was successfully created.' }
        format.json { render :show, status: :created, location: @what_test }
      else
        format.html { render :new }
        format.json { render json: @what_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /what_tests/1
  # PATCH/PUT /what_tests/1.json
  def update
    respond_to do |format|
      if @what_test.update(what_test_params)
        format.html { redirect_to @what_test, notice: 'What test was successfully updated.' }
        format.json { render :show, status: :ok, location: @what_test }
      else
        format.html { render :edit }
        format.json { render json: @what_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /what_tests/1
  # DELETE /what_tests/1.json
  def destroy
    @what_test.destroy
    respond_to do |format|
      format.html { redirect_to what_tests_url, notice: 'What test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_what_test
      @what_test = WhatTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def what_test_params
      params.require(:what_test).permit(:period_id, :testname)
    end
end

exapp/app/helpers/what_tests_helper.rb
module WhatTestsHelper
end

exapp/app/views/what_tests/_form.html.erb
<%= form_with(model: what_test, local: true) do |form| %>
  <% if what_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(what_test.errors.count, "error") %> prohibited this what_test from being saved:</h2>

      <ul>
      <% what_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :period_id ,'期間' %>
    <%= form.collection_select :period_id ,Period.all,:id,:periodname,{include_blank: true}  %>
  </div>

  <div class="field">
    <%= form.label :testname ,'テスト名' %>
    <%= form.text_field :testname %>
  </div>

  <div class="actions">
    <%= form.submit "作成" %>
  </div>

<% end %>

exapp/app/views/what_tests/edit.html.erb
<h1>テスト科目編集画面</h1>

<%= render 'form', what_test: @what_test %>

<%= link_to '詳細', @what_test %> |
<%= link_to '戻る', what_tests_path %>

exapp/app/views/what_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>テストの種類</h1>

<table class="table">
  <thead>
    <tr>
      <th>期間</th>
      <th>テスト名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @what_tests.each do |what_test| %>
      <tr>
        <td><%= what_test.period.periodname %></td>
        <td><%= what_test.testname %></td>
        <td><%= link_to '詳細', what_test %></td>
        <td><%= link_to '編集', edit_what_test_path(what_test) %></td>
        <td><%= link_to '削除', what_test, method: :delete, data: { confirm: '削除してもよろしいですか' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規テスト作成', new_what_test_path %>

exapp/app/views/what_tests/new.html.erb
<h1>テスト作成フォーム</h1>

<%= render 'form', what_test: @what_test %>

<%= link_to '戻る', what_tests_path %>

exapp/app/views/what_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>期間:</strong>
  <%= @what_test.period.periodname %>
</p>

<p>
  <strong>テスト名:</strong>
  <%= @what_test.testname %>
</p>

<%= link_to '編集', edit_what_test_path(@what_test) %> |
<%= link_to '戻る', what_tests_path %>