exapp/config/routes.rb
Rails.application.routes.draw do
  resources :test_results
  resources :users
  resources :what_tests
  resources :periods

  get '/' => 'test_results#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

exapp/app/models/user.rb
class User < ApplicationRecord
  validates :name,:grade,presence: true
  validates :grade,inclusion: {in: 1..6 }
end

exapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @test_results = TestResult.all
    @user_grade1 = User.where("grade = ?",1)
    @user_grade2 = User.where("grade = ?",2)
    @user_grade3 = User.where("grade = ?",3)
    @user_grade4 = User.where("grade = ?",4)
    @user_grade5 = User.where("grade = ?",5)
    @user_grade6 = User.where("grade = ?",6)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @test_results = TestResult.where("user_id = ?",params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :grade)
    end
end

exapp/app/helpers/users_helper.rb
module UsersHelper
end

exapp/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name ,'生徒名' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :grade ,'学年' %>
    <%= form.number_field :grade %>
  </div>

  <div class="actions">
    <%= form.submit "作成" %>
  </div>
<% end %>

exapp/app/views/users/edit.html.erb
<h1>生徒情報編集画面</h1>

<%= render 'form', user: @user %>

<%= link_to '詳細', @user %> |
<%= link_to '戻る', users_path %>

exapp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>生徒一覧</h1>
<div class="p-4">

  <table class="table card-body bg-light p-5">
    <thead>
    <tr>
      <th>生徒名</th>
      <th>学年</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.grade %></td>
        <td><%= link_to '詳細', user %></td>
        <td><%= link_to '編集', edit_user_path(user) %></td>
        <td><%= link_to '削除', user, method: :delete, data: {confirm: '削除しますか?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>

<div class="p-4">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a href="#tab1" class="nav-link active" data-toggle="tab">1年生</a>
    </li>
    <li class="nav-item">
      <a href="#tab2" class="nav-link" data-toggle="tab">2年生</a>
    </li>
    <li class="nav-item">
      <a href="#tab3" class="nav-link" data-toggle="tab">3年生</a>
    </li>
    <li class="nav-item">
      <a href="#tab4" class="nav-link" data-toggle="tab">4年生</a>
    </li>
    <li class="nav-item">
      <a href="#tab5" class="nav-link" data-toggle="tab">5年生</a>
    </li>
    <li class="nav-item">
      <a href="#tab6" class="nav-link" data-toggle="tab">6年生</a>
    </li>
  </ul>

  <div class="tab-content card mb-3">
    <div id="tab1" class="tab-pane active">
      <table class="table">
        <thead>
        <tr>
          <th>生徒名</th>
          <th>1年生</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @user_grade1.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.grade %></td>
            <td><%= link_to '詳細', user %></td>
            <td><%= link_to '編集', edit_user_path(user) %></td>
            <td><%= link_to '削除', user, method: :delete, data: {confirm: '削除しますか?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div id="tab2" class="tab-pane">
      <table class="table">
        <thead>
        <tr>
          <th>生徒名</th>
          <th>2年生</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @user_grade2.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.grade %></td>
            <td><%= link_to '詳細', user %></td>
            <td><%= link_to '編集', edit_user_path(user) %></td>
            <td><%= link_to '削除', user, method: :delete, data: {confirm: '削除しますか?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div id="tab3" class="tab-pane">
      <table class="table">
        <thead>
        <tr>
          <th>生徒名</th>
          <th>3年生</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @user_grade3.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.grade %></td>
            <td><%= link_to '詳細', user %></td>
            <td><%= link_to '編集', edit_user_path(user) %></td>
            <td><%= link_to '削除', user, method: :delete, data: {confirm: '削除しますか?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div id="tab4" class="tab-pane">
      <table class="table">
        <thead>
        <tr>
          <th>生徒名</th>
          <th>4年生</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @user_grade4.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.grade %></td>
            <td><%= link_to '詳細', user %></td>
            <td><%= link_to '編集', edit_user_path(user) %></td>
            <td><%= link_to '削除', user, method: :delete, data: {confirm: '削除しますか?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div id="tab5" class="tab-pane">
      <table class="table">
        <thead>
        <tr>
          <th>生徒名</th>
          <th>5年生</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @user_grade5.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.grade %></td>
            <td><%= link_to '詳細', user %></td>
            <td><%= link_to '編集', edit_user_path(user) %></td>
            <td><%= link_to '削除', user, method: :delete, data: {confirm: '削除しますか?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div id="tab6" class="tab-pane">
      <table class="table">
        <thead>
        <tr>
          <th>生徒名</th>
          <th>6年生</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @user_grade6.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.grade %></td>
            <td><%= link_to '詳細', user %></td>
            <td><%= link_to '編集', edit_user_path(user) %></td>
            <td><%= link_to '削除', user, method: :delete, data: {confirm: '削除しますか?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to '新規生徒作成', new_user_path %>

exapp/app/views/users/new.html.erb
<h1>生徒登録フォーム</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', users_path %>

exapp/app/views/users/show.html.erb
<h1>  <%= @user.name %> のデータ詳細画面</h1>
<p id="notice"><%= notice %></p>

<h4>
  <strong>学年:</strong>
  <%= @user.grade %>
</h4>

<table class="table">
  <thead>
  <tr>
    <th>期間</th>
    <th>テスト名</th>
    <th>国語</th>
    <th>数学</th>
    <th>英語</th>
    <th>理科</th>
    <th>社会</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @test_results.each do |test_result| %>
    <tr>
      <td><%= test_result.what_test.period.periodname %></td>
      <td><%= test_result.what_test.testname %></td>
      <td><%= test_result.jpn %></td>
      <td><%= test_result.math %></td>
      <td><%= test_result.eng %></td>
      <td><%= test_result.sci %></td>
      <td><%= test_result.soc %></td>
      <td><%= link_to '詳細', test_result, {:class => "btn btn-primary"} %></td>
      <td><%= link_to '編集', edit_test_result_path(test_result), {:class => "btn btn-primary"} %></td>
      <td><%= link_to '削除', test_result, method: :delete, data: {confirm: '削除しますか?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

  <%= link_to '編集', edit_user_path(@user) %> |
  <%= link_to '戻る', users_path %>