exapp/config/routes.rb
Rails.application.routes.draw do
  resources :test_results
  resources :users
  resources :what_tests
  resources :periods

  get '/' => 'test_results#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

exapp/app/models/period.rb
class Period < ApplicationRecord
end

exapp/app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period.destroy
    respond_to do |format|
      format.html { redirect_to periods_url, notice: 'Period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:periodname)
    end
end

exapp/app/helpers/periods_helper.rb
module PeriodsHelper
end

exapp/app/views/periods/_form.html.erb
<%= form_with(model: period, local: true) do |form| %>
  <% if period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :periodname %>
    <%= form.text_field :periodname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

exapp/app/views/periods/edit.html.erb
<h1>Editing Period</h1>

<%= render 'form', period: @period %>

<%= link_to 'Show', @period %> |
<%= link_to 'Back', periods_path %>

exapp/app/views/periods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Periods</h1>

<table>
  <thead>
    <tr>
      <th>Periodname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= period.periodname %></td>
        <td><%= link_to 'Show', period %></td>
        <td><%= link_to 'Edit', edit_period_path(period) %></td>
        <td><%= link_to 'Destroy', period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Period', new_period_path %>

exapp/app/views/periods/new.html.erb
<h1>New Period</h1>

<%= render 'form', period: @period %>

<%= link_to 'Back', periods_path %>

exapp/app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Periodname:</strong>
  <%= @period.periodname %>
</p>

<%= link_to 'Edit', edit_period_path(@period) %> |
<%= link_to 'Back', periods_path %>